import RestaurantNavbar from '../components/RestaurantNavbar';
import Menu from '../components/Menu';
import { PrismaClient } from '@prisma/client';

export const metadata = {
  title: 'Restaurant Menu',
  description: 'Generated by create next app',
};

const prisma = new PrismaClient();

const fetchRestaurantMenu = async (slug: string) => {
  const restaurant = await prisma.restaurant.findUnique({
    where: {
      slug,
    },
    select: {
      items: true,
    },
  });

  if (!restaurant) {
    throw new Error();
  }

  return restaurant.items;
};

export default async function MenuPage({
  params,
}: {
  params: { slug: string };
}) {
  const menu = await fetchRestaurantMenu(params.slug);
  return (
    <>
      <div className='bg-white w-[100%] rounded p-3 shadow'>
        <RestaurantNavbar slug={params.slug} />
        <Menu menu={menu}/>
      </div>
    </>
  );
}
