import RestaurantNavbar from '../components/RestaurantNavbar';
import Menu from '../components/Menu';

export const metadata = {
  title: 'Restaurant Menu',
  description: 'Generated by create next app',
};

export default function MenuPage() {
  return (
    <>
        <div className='bg-white w-[100%] rounded p-3 shadow'>
          <RestaurantNavbar />
          <Menu />
        </div>
    </>
  );
}
