import Header from './components/Header';
import RestaurantCard from './components/RestaurantCard';
import SearchSidebar from './components/SearchSidebar';
import { PrismaClient } from '@prisma/client';

export const metadata = {
  title: 'Search',
  description: 'Generated by create next app',
};

const prisma = new PrismaClient();

const fetchRestaurantsByCity = (city: string) => {
  // return all restaurants if no search params
  if (!city) return prisma.restaurant.findMany();

  return prisma.restaurant.findMany({
    where: {
      location: {
        name: {
          equals: city,
        },
      },
    },
  });
};

export default async function Search({
  searchParams,
}: {
  searchParams: { city: string };
}) {
  const restaurants = await fetchRestaurantsByCity(
    searchParams.city.toLowerCase()
  );

  return (
    <>
      <Header />
      <div className='flex items-start justify-between w-2/3 py-4 m-auto'>
        <SearchSidebar />
        <div className='w-5/6'>
          <RestaurantCard />
        </div>
      </div>
    </>
  );
}
